spring.application.name=Feedback-Prod
# Use the same database host, but you could point to a 'Feedback_Prod' DB name if you create one
spring.datasource.url=jdbc:postgresql://postgres-db:5432/Feedback
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true